language: python

branches:
  except:
    - gh-pages

python:
  - "2.7"

env:
  global:
    - MONGODB_URI=mongodb://localhost:27017

  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=pypy

services:
  - mongodb

install:
  - pip install tox --use-mirrors

script: tox
